Map marker track
lbratkovskaya/flightradar-clone pull request #1
Opened 2021-01-24 08:56 UTC by lbratkovskaya

Map with aircrafts, airports and flight tracks

2021-01-24 19:25 UTC, OlgaSenyushkina requested changes

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/utils/apiUtils.ts
> +  interface AccessObject {
интерфейсы лучше держать в отдельном файле, не стоит их объявлять внутри функции

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/utils/apiUtils.ts
> +  } = mapAccessObj;
ты сначала создаешь объект, а затем его деструктурируешь, но сам объект нигде не используется. Может стоит в таком случае не создавать объект, а ключи объекта mapAccessObj объявить как константы?

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/utils/apiUtils.ts
> +const roundingCoeff = 1000;
это можно вынести в отдельный файл с константами

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/utils/apiUtils.ts
> +const DEFAULT_ICAO = 'B738';
это можно вынести в отдельный файл с константами

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/utils/apiUtils.ts
> +const roundingCoeff = 1000;
и подобные константы пишем, используя uppercase

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/types/AirportsLayerType.ts
> +  airportsMap: {
для данного поля тоже давай пропишем интерфейс?

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/types/AirportsLayerType.ts
> +  name:string,
нужны отступы после :

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/types/FlightsLayerType.ts
> +import { AircraftsMap } from '.';
путь лучше прописать относительный, т.е. так "./"

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/types/index.d.ts
> +export interface AircraftState {
в данном интерфейсе есть такие же поля, как и в AircraftPosition. 
Возможно, есть смысл их группировать одним ключом и присвоить ему интерфейс AircraftPosition.

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsMap/index.tsx
> +        scrollWheelZoom={true}
в jsx если пропс имеет значение true, то мы можем просто прописать его без присваивания значения. 
Т.е. можно так:
<MapContainer
        center={geoPosition}
        zoom={mapZoom}
        scrollWheelZoom
        whenCreated={this.setMapView // здесь ссылка на метод, нужно назвать корректнее}

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsMap/index.tsx
> +          map.locate({ setView: true, maxZoom: 8 });
давай вынесем в отдельный метод в компоненте и будем передавать здесь на него ссылку, чтобы с каждым рендером не создавалась новая функция?
например, whenCreated={this.setMapView}

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsMap/index.tsx
> +      geoPosition: latLng(50.41111, 80.2275),
"магические" координаты стоит вынести в константы с говорящим названием)

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsLayer/index.tsx
> +                callsign: stateArr[13],
данный объект стоит вынести в константу внутри данного метода и использовать её здесь и на 79-й строке?

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsLayer/index.tsx
> +          Object.keys(json).filter((key) => !['full_count', 'version'].includes(key))?.forEach((flightId: string) => {
давай разобьём на несколько констант, очень сложно для понимания что делаем и зачем.

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsLayer/index.tsx
> +        this.setState((state) => {
не стоит выполнять сложные вычисления внутри setState. Лучше ниже описанную логику вынести в отдельный метод, а в setState уже использовать результат вычислений.

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsLayer/index.tsx
> +          let { trackLatLngs: latLngs } = state;
здесь ты присваиваешь ссылку на значение из стейта и ниже на 120-ой строке его мутируешь. 
Объект состояния не должен мутировать. Изменения должны проявляться в виде нового объекта на основе входных данных из state и props. (https://ru.reactjs.org/docs/react-component.html)

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsLayer/AircraftMarker.tsx
> +        mouseout: (e) => e.target.closePopup(),
здесь лучше прокидывать ссылку на метод, чтобы каждый рендер не пересоздавать новую функцию.

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsLayer/AircraftMarker.tsx
> +      this.markerRef.current.setIcon(this.getIcon(
здесь лучше перестраховаться и использовать optional chaining для ключа current

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/FlightsLayer/AircraftMarker.tsx
> +  UNSAFE_componentWillReceiveProps = (newProps: AircraftMarkerProps): void => {
componentWillReceiveProps - этот метод жизненного цикла является deprecated (https://ru.reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops).
Вместо него для сравнения предыдущего и нового/текущего значения пропсов рекомендую использовать componentDidUpdate

2021-01-24 19:25 UTC, OlgaSenyushkina commented on src/components/AirportsLayer/index.tsx
> +        this.setState((state) => {
Стоит вынести логику из setState и использовать только результат вычислений для формирования нового значения стейта

2021-01-26 06:49 UTC, lbratkovskaya commented on src/utils/apiUtils.ts
> +const roundingCoeff = 1000;
данная константа не используется вне файла apiUtils, стоит ли выносить в таком случае?

2021-01-26 06:49 UTC, lbratkovskaya commented on src/utils/apiUtils.ts
> +const DEFAULT_ICAO = 'B738';
данная константа не используется вне файла apiUtils, стоит ли выносить в таком случае?

2021-01-26 14:06 UTC, lbratkovskaya commented on src/components/FlightsLayer/index.tsx
> +        this.setState((state) => {
Пока не понимаю, как сделать иначе: новый стейт вычисляется на основе текущего значения, для существующих объектов данные должны быть дополнены, для отсутствующих - добавлены. Либо придётся проходить по циклу дважды - первый раз, трансформируя данные из респонса, второй - сливая их с текущим стейтом

2021-01-26 14:33 UTC, lbratkovskaya commented on src/components/FlightsLayer/AircraftMarker.tsx
> +  UNSAFE_componentWillReceiveProps = (newProps: AircraftMarkerProps): void => {
К сожалению, componentDidUpdate не подходит: он не позволяет отменить перерисовку. Из-за этого иконки самолётов моргают при обновлении state. Данный метод позволяет запретить перерисовывать и сдвинуть позицию маркера средствами leaflet

2021-01-26 15:11 UTC, lbratkovskaya commented on src/types/FlightsLayerType.ts
> +import { AircraftsMap } from '.';
eslint ругается:

Useless path segments for "./", should be "."  import/no-useless-path-segments

2021-01-31 09:44 UTC, Christina-Kashevar commented on src/components/AirportsLayer/index.tsx
> +        iconAnchor: [20, 20],
возможно ли занести размеры в константу?

2021-01-31 10:00 UTC, Christina-Kashevar commented on src/components/FlightsMap/index.tsx
> +  }
возможно тоже maxzoom в константы перевести

2021-01-31 10:06 UTC, Christina-Kashevar reviewed
Есть только пару замечаний по константам, так все отлично)

2021-01-31 10:25 UTC, Christina-Kashevar approved these changes

2021-01-31 10:45 UTC, babkinevgeny approved these changes

2021-01-31 11:22 UTC, OlgaSenyushkina approved these changes

2021-01-31 11:22 UTC, OlgaSenyushkina commented on src/utils/apiUtils.ts
> +const roundingCoeff = 1000;
Почему бы тогда не поместить данную константу в саму функцию roundCoordinates, если она нигде больше не используется?

2021-01-31 11:22 UTC, OlgaSenyushkina commented on src/utils/apiUtils.ts
> +const DEFAULT_ICAO = 'B738';
Аналогичною Почему бы тогда не поместить данную константу в саму функцию getIconByAircraft, если она нигде больше не используется?

2021-01-31 11:25 UTC, merged