Airport
lbratkovskaya/flightradar-clone pull request #3
Opened 2021-01-26 15:43 UTC by Christina-Kashevar

2021-01-27 07:57 UTC, lbratkovskaya requested changes
В целом много мест, в которых не хватает пробелов. Прогони, пожалуйста, eslint, он покажет все такие места

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Airport.scss
> +  // overflow: hidden;
Давай избавляться от всех комментариев в коде

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Airport.tsx
> +  const [openPanel, setOpenPanel] = useState(openAirportPanel);
Компонент с таким количествой полей состояния лучше переделать на классовый

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Airport.tsx
> +        const satelliteImageData = data.result.response.airport.pluginData.satelliteImage;
Здесь просится деструктуризация объекта data.result.response.airport.pluginData

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Airport.tsx
> +    <div id="airport" style={{ transform: openPanel ? 'translateX(0)' : 'translateX(-100vw)' }}>
Нельзя ли это перенести в css-класс? инлайн-стили очень плохо поддаются переопределению, случись такая нужда

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Airport.tsx
> +      ) : null}
Хорошо бы эти вычисления произвести до открытия тега _div_, а лучше даже в отдельных методах. Когда вёрстка так перемешана с вычислениями, очень тяжело читать код

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Airport.tsx
> +      ))}
Просится метод getButtons, который вернёт нам этот набор компонентов

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/AirportPhoto/AirportPhoto.tsx
> +const AirportPhoto:React.FC<AirportPhotoProps> = ({ airportInfo }:AirportPhotoProps)
Пробел после : потерялся

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/AirportPhoto/AirportPhoto.tsx
> +interface AirportPhotoProps {
Интерфейс лучше вынести в отдельный файл в папке types, например, AirportPhotoTypes.ts

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/ArrivalsAndDepartures.tsx
> +      if (day === getLocalData(flights[i].flight.time.scheduled[modeInSingle],
Может быть, вынесем результат getLocalData(...) в константу? Чуть проще будет читать

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/ArrivalsAndDepartures.tsx
> +    for (let i = 0, j = 0; i < flights.length; i += 1) {
В первой итерации этого цикла мы заново вычислим beginningDate. Нельзя ли от этого избавиться?

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/ArrivalsAndDepartures.tsx
> +          ))}
Все вычисления хочется вынести в отдельные методы

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/FlightHeader/FlightHeader.scss
> +  background-color: #D1d0d0;
Upper-case или lower-case? Давай выберем что-то одно))

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/ArrivalsAndDepartures.tsx
> +interface ArrivalsProps {
Давай вынесем интерфейс в отдельный файл?

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/FlightHeader/FlightHeader.tsx
> +interface FlightHeaderProps {
Давай вынесем интерфейс в отдельный файл?

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/OneFlight/OneFlight.scss
> +    background:#f9f9fb;
Пробел потерялся после :

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/OneFlight/OneFlight.scss
> +    &-airport span{
Пробел перед { пропал

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/OneFlight/OneFlight.scss
> +    &-aircraft span{
И тут пробел пропал

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/OneFlight/OneFlight.tsx
> +        <img src={`https://cdn.flightradar24.com/assets/airlines/logotypes/${airlineCodeIata}_${airlineCodeIcao}.png`} alt="logo" />
Хорошо бы вынести ссылку в константу перед return

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Button/Button.scss
> +      fill:#f8C023;
Пробел после : пропал

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Button/Button.tsx
> +  changeTabHandler:ChangeTabHandler
Запятая в конце нужна

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Button/Button.tsx
> +}:ButtonProps) => {
Пробел после :

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Button/Button.tsx
> +const Button:React.FC<ButtonProps> = ({
Есть ощущение, что подобный компонент может пригодиться нам для панели информации о рейсе. Может быть, вынести этот компонент наружу для последующего переиспользования? То же про Header

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Button/Button.tsx
> +      changeTabHandler(+e.target.dataset.name);
Можно было бы менять только аргумент в зависимости от результатов проверки:

const tabHandlerTarget = (e.target instanceof HTMLButtonElement) ? +e.target.dataset.name : +e.target.parentElement.dataset.name;

changeTabHandler(tabHandlerTarget);

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Button/Button.tsx
> +      className={active === num ? 'airport-button airport-button-active' : 'airport-button'}
'airport-button' общий класс. Можно так:

 className={\`airport-button ${active === num ? 'airport-button-active' : ''}\`}

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Runway/Runway.tsx
> +            {runways.map((item) => (
Хорошо бы вынести вычисления в метод типа getRunways

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ScheduledFlights/ScheduledFlights.tsx
> +    <h2 className="airport-schedule__name">SCHEDULED FLIGHTS - NEXT 7 DAYS</h2>
7 выглядит как "магическая константа": если завтра нам захочется поменять период на 10 дней или 30, это потребует изменений в нескольких местах кода. Давай вынесем размер этого периода в константы и будем использовать эту константу и здесь в заголовках, и для вычисления периода при получении данных

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/ScheduledFlights/ScheduledFlights.tsx
> +            href={`https://www.flightradar24.com/data/airports/${schedule.topRoute.from.toLowerCase()}/routes`}
Ссылку тоже хочется загнать в константу либо в метод утилит

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Weather/Weather.tsx
> +type Temp = {temp:number, 'feels_like':number, 'temp_min':number, 'temp_max':number, pressure:number, humidity:number, 'sea_level':number, 'grnd_level':number};
Странные строковые ключи

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Weather/Weather.tsx
> +    fetch(`https://api.openweathermap.org/data/2.5/weather?lat=${airportInfo.position.latitude}&lon=${airportInfo.position.longitude}&lang=en&appid=1f22d4f798f3fa7006bf7a2c8aec93c5&units=metric`)
Давай ссылку загоним в метод-утилиту

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/Airport/Weather/Weather.tsx
> +    url = `https://openweathermap.org/img/wn/${weatherInfo.icon}.png`;
И эту ссылку тоже в утилиту

2021-01-27 07:57 UTC, lbratkovskaya commented on src/components/App/App.tsx
> +  const code = 'MSQ';
Давай перенесём эту строку в константы

2021-01-27 07:57 UTC, lbratkovskaya commented on src/img/Arrivals.tsx
> +const Arrivals = (): JSX.Element => (
Меня смущает react-компонент в папке img. Может быть, оставить здесь файл svg с соответствующим содержимым, а компонент перенести к компонентам?

2021-01-27 07:57 UTC, lbratkovskaya commented on src/types/types.d.ts
> +type Photo = {
Давай переименуем этот файл так, чтобы было понятно, какие именно типы в нём хранятся. Например, AirportDataTypes.d.ts

2021-01-27 07:57 UTC, lbratkovskaya commented on src/utils/getLocalData.tsx
> +  const tzoffset = (new Date()).getTimezoneOffset() * 60000; // offset in milliseconds
Давай перенесём "магические константы" в файл констант?

2021-01-27 07:57 UTC, lbratkovskaya commented on webpack.config.js
> +      // }),
Если мы закомментируем этот кусок кода, иконки спрайтов самолётов не попадут в итоговую сборку.

2021-01-27 07:57 UTC, lbratkovskaya commented on webpack.config.js
> +        // favicon: "./src/img/jet.svg",
Не подскажешь, зачем ты закомментировала фавиконку?

2021-01-28 12:07 UTC, Christina-Kashevar commented on src/components/Airport/Airport.tsx
> +        const satelliteImageData = data.result.response.airport.pluginData.satelliteImage;
Да, действительно. Упустила из виду

2021-01-28 12:07 UTC, Christina-Kashevar commented on src/components/Airport/Airport.scss
> +  // overflow: hidden;
Не пересмотрела перед отправкой, удалю

2021-01-28 12:10 UTC, Christina-Kashevar commented on src/components/Airport/Airport.tsx
> +  const [openPanel, setOpenPanel] = useState(openAirportPanel);
Т к вся ветка сделана на хуках, я придерживалась такой структуры. Это не будет странно, если родительский компонент на классе, а дочерние на хуках?

2021-01-28 12:10 UTC, Christina-Kashevar commented on src/components/Airport/Airport.tsx
> +    <div id="airport" style={{ transform: openPanel ? 'translateX(0)' : 'translateX(-100vw)' }}>
Можно)

2021-01-28 12:21 UTC, Christina-Kashevar commented on src/components/App/App.tsx
> +  const code = 'MSQ';
это временная константа для разработки, она будет получаться от клика на карту

2021-01-28 12:22 UTC, Christina-Kashevar commented on webpack.config.js
> +      // }),
в моей ветки нет этой папки, поэтому ошибка при компиляции возникает. В итоговом варианте, это конечно будет раскомичено

2021-01-28 12:22 UTC, Christina-Kashevar commented on webpack.config.js
> +        // favicon: "./src/img/jet.svg",
в моей ветки нет этой папки, поэтому ошибка при компиляции возникает. В итоговом варианте, это конечно будет раскомичено

2021-01-28 14:22 UTC, Christina-Kashevar commented on src/components/Airport/Button/Button.tsx
> +const Button:React.FC<ButtonProps> = ({
Возможно вынесу, буду смотреть, когда дойду до реализации панели информации о рейсе, будут ли там кнопки и какие

2021-01-28 14:25 UTC, Christina-Kashevar commented on src/components/Airport/ArrivalsAndDepartures/FlightHeader/FlightHeader.scss
> +  background-color: #D1d0d0;
не поняла, о чем речь)) там только  Upper-case

2021-01-28 14:59 UTC, Christina-Kashevar commented on src/components/Airport/Weather/Weather.tsx
> +    url = `https://openweathermap.org/img/wn/${weatherInfo.icon}.png`;
А это не будет излишним? тут только одна переменная, если создавать для нее утилиту получится больше кода

2021-01-28 15:35 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/FlightHeader/FlightHeader.scss
> +  background-color: #D1d0d0;
background-color: #d1d0d0;
или
background-color: #D1D0D0;

Давай выберем один из этим вариантов)

2021-01-28 15:37 UTC, lbratkovskaya commented on src/components/Airport/Airport.tsx
> +  const [openPanel, setOpenPanel] = useState(openAirportPanel);
Дочерние в смысле вложенные? Нет, совсем не странно. Логика в том, чтобы делать stateful-компоненты классовыми, а stateless - функциональными

2021-01-28 15:41 UTC, lbratkovskaya commented on src/components/Airport/Weather/Weather.tsx
> +    url = `https://openweathermap.org/img/wn/${weatherInfo.icon}.png`;
Я предлагаю сделать в apiUtils такой метод:

getWeatherUrl = (weatherInfo) => {
 return (weatherInfo) ? `https://openweathermap.org/img/wn/${weatherInfo.icon}.png` : null;
}

а в компоненте тогда использовать:

      <div className="airport-weather__conditions">
        <span className="airport-weather_upperCase">CONDITIONS</span>
        <img src={getWeatherUrl} alt="weather-icon" />
       ...

2021-01-29 08:21 UTC, Christina-Kashevar commented on src/components/Airport/ArrivalsAndDepartures/FlightHeader/FlightHeader.scss
> +  background-color: #D1d0d0;
ааа, там у меня просто текст в Upper-case  самой верстке, думала, ты про него))

2021-01-29 08:35 UTC, Christina-Kashevar commented on src/components/Airport/Weather/Weather.tsx
> +    url = `https://openweathermap.org/img/wn/${weatherInfo.icon}.png`;
Хороший вариант. Спасибо!

2021-01-31 05:18 UTC, lbratkovskaya requested changes

2021-01-31 05:18 UTC, lbratkovskaya commented on src/components/Airport/Airport.tsx
> +  AirportInfo, Schedule, Runways, AirportProps,
Давай придерживаться структуры, предлагаемой eslint: если открывающся и закрывающия скобка на разных строках, то элементы перечисления также каждый в своей строке

2021-01-31 05:18 UTC, lbratkovskaya commented on src/components/Airport/Weather/Weather.tsx
> +  const [wind, setWind] = useState<{speed: number, deg: number} | null>(null);
А чего решила от типа отказаться?

2021-01-31 05:18 UTC, lbratkovskaya commented on src/utils/airportConstants.ts
> +export const futurePeriod = 7;
Если эти константы используются только в методе getLocalData(..), то можно их не экспортировать, а внести просто в тело метода

2021-01-31 05:18 UTC, lbratkovskaya commented on src/utils/separateFlightsBeDate.tsx
> +        flights[i].flight.airport.origin.timezone.offset).getDay();
Было бы круто здесь тоже деструктуризировать

2021-01-31 05:18 UTC, lbratkovskaya commented on src/components/Airport/Button/Button.tsx
> +import Departures from '../SVGComponents/Departures';
А в одну строчку не запишется? Типа:
import { General, Arrivals, Departures } from '../SVGComponents';
?

2021-01-31 05:18 UTC, lbratkovskaya commented on src/components/Airport/ArrivalsAndDepartures/OneFlight/OneFlight.tsx
> +  img.src = `https://cdn.flightradar24.com/assets/airlines/logotypes/${airlineCodeIata}_${airlineCodeIcao}.png`;
Давай ссылки тоже в утильные методы? Тогда эти методы можно назвать так, чтобы было понятно, почему мы два раза запрашиваем данные одной картинки

2021-01-31 10:38 UTC, Christina-Kashevar commented on src/components/Airport/Button/Button.tsx
> +import Departures from '../SVGComponents/Departures';
не получилось, нужна ссылка на файл, а не папку

2021-01-31 10:49 UTC, babkinevgeny approved these changes

2021-01-31 13:37 UTC, OlgaSenyushkina requested changes

2021-01-31 13:37 UTC, OlgaSenyushkina commented on src/components/Airport/Airport.tsx
> +      {airportInfo ? <Header airportInfo={airportInfo} closeHandler={closeHandler} /> : null}
можно заменить на `{!!airportInfo && <Header airportInfo={airportInfo} closeHandler={closeHandler} /> }`

2021-01-31 13:37 UTC, OlgaSenyushkina commented on src/components/Airport/Airport.tsx
> +      {activeTab === 1 && airportInfo && schedule && satelliteImageData ? (
условие можно вынести в константу и аналогично избавиться от `: null`

2021-01-31 13:37 UTC, OlgaSenyushkina commented on src/components/Airport/Airport.tsx
> +      {activeTab === 1 && airportInfo && schedule && satelliteImageData ? (
так же для других табов ниже

2021-01-31 13:37 UTC, OlgaSenyushkina commented on src/components/Airport/ArrivalsAndDepartures/ArrivalsAndDepartures.scss
> +
лишний отступ

2021-01-31 13:37 UTC, OlgaSenyushkina commented on src/components/Airport/ArrivalsAndDepartures/ArrivalsAndDepartures.tsx
> +  const modeInSingle = mode === 'arrivals' ? 'arrival' : 'departure';
достаточно 1 раз сравнить mode === 'arrivals' и присвоить константе, а затем использовать её здесь и ниже по коду

2021-01-31 13:37 UTC, OlgaSenyushkina commented on src/components/Airport/ArrivalsAndDepartures/ArrivalsAndDepartures.tsx
> +                aircraftModel={flight.flight.aircraft.model.code}
давай деструктурируем эти значения, чтобы по нескольку раз не перебирать одни и те же ключи?

2021-01-31 13:37 UTC, OlgaSenyushkina commented on src/components/Airport/ArrivalsAndDepartures/ArrivalsAndDepartures.tsx
> +          <React.Fragment key={Math.random()}>
Не стоит использовать Math.random() для генерации уникального ключа, так как он не гарантирует нам, что рандомно полученное значение не повторится при переборе следующих элементов. Лучше формируй как строку + индекс элемента, например: key={`flightsDay_${i}`}. Таким образом мы точно избежим дублирование ключа

2021-01-31 13:37 UTC, OlgaSenyushkina commented on src/components/Airport/Header/Header.tsx
> +  const flagUrl = `https://www.countryflags.io/${airportInfo.position.country.code}/flat/64.png`;
иконку через /api тоже будем доставать?

2021-01-31 13:37 UTC, OlgaSenyushkina commented on webpack.config.js
> +        // favicon: "./src/img/jet.svg",
можно раскомментить?

2021-01-31 13:37 UTC, OlgaSenyushkina commented on webpack.config.js
> +      // new CopyWebpackPlugin({
можно раскомментить?

2021-01-31 15:35 UTC, OlgaSenyushkina approved these changes

2021-01-31 16:16 UTC, lbratkovskaya approved these changes

2021-01-31 16:17 UTC, merged

2021-02-08 16:42 UTC, Christina-Kashevar commented on src/components/Airport/Header/Header.tsx
> +  const flagUrl = `https://www.countryflags.io/${airportInfo.position.country.code}/flat/64.png`;
к сожалению да