init: server refactoring
lbratkovskaya/flightradar-clone pull request #6
Opened 2021-01-31 15:12 UTC by babkinevgeny

2021-01-31 15:20 UTC, OlgaSenyushkina approved these changes

2021-01-31 16:08 UTC, Christina-Kashevar approved these changes

2021-01-31 16:50 UTC, lbratkovskaya requested changes

2021-01-31 16:50 UTC, lbratkovskaya commented on server/api/router.js
> +
Нужно добавить Кристинины методы:

```
apiRouter.route('/rating').get(async (req, res) => {
  await https.get(`https://www.flightradar24.com/airports/myfr24-ratings?iata=${req.query.airportCode}`, responseHandler(res))
});

apiRouter.route('/flag').get(async (req, res) => {
  await https.get(`https://www.countryflags.io/${req.query.countryCode}/flat/64.png`, responseHandler(res))
});

```

2021-02-01 17:00 UTC, lbratkovskaya approved these changes

2021-02-01 18:07 UTC, merged