Flight panel
lbratkovskaya/flightradar-clone pull request #7
Opened 2021-01-31 16:46 UTC by Christina-Kashevar

2021-01-31 17:22 UTC, lbratkovskaya requested changes
1 Не хотелось бы удалять и переносить файлы из папки src/img.
2 Ты прогоняла линтер? Много пропущенных пробелов и запятых
3 Много мест, в которых использование строк шаблонизаторы сильно упростило бы читаемость

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/AircraftInfo/AircraftInfo.tsx
> +interface AircraftInfoProps {
Давай вынесем интерфейс в отдельный файл

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/AircraftInfo/AircraftInfo.tsx
> +  if (!isLoadedFromFirst) {
Таймаута не хватает.  При такой реализации у тебя всегда будет вызываться второй api из-за асинхронности

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/AircraftInfo/AircraftInfo.tsx
> +              {') '}
1. Открывающая скобка вне span, закрывающая - внутри. Давай к единому виду приведём.
2. Давай всю эту конструкцию засунем в строку шаблонизатора:
```
<span> { ` (${model.code}) ` }</span>
```

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/AircraftPhoto/AircraftPhoto.tsx
> +const AircraftPhoto:React.FC<AircraftPhotoProps> = ({ photo, photoLink }:AircraftPhotoProps)
Пробел потерялся

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/AircraftPhoto/AircraftPhoto.tsx
> +interface AircraftPhotoProps {
Интерфейс в отдельный файл хотелось бы. И запятых не хватает

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/AircraftPhoto/AircraftPhoto.tsx
> +:JSX.Element => (
И тут пробел

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/Altitude/Altitude.scss
> +.flight-altitude{
Пробел пропал)

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/Altitude/Altitude.tsx
> +            ft
Можно чуть короче и симпатичнее:
```
`${alt} ft`
```

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/Altitude/Altitude.tsx
> +            {' °'}
Тут тоже шаблонизатор просится

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/Flight.tsx
> +  hexCode: string
Зпт

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/Flight.tsx
> +const FlightPanel = ({ hexCode, openFlightPanel }:FlightPanelProps):JSX.Element => {
Двух пробелов не досчиталась

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/Flight.tsx
> +    <div className="flight" style={{ transform: openPanel ? 'translateX(0)' : 'translateX(-100vw)' }}>
Может, тоже в css-класс, как делали для аэропортов?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/Flight.tsx
> +            timezoneDestination={flightInfo.airport.destination.timezone}
Деструктуризация просится

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/FlightData/FlightData.tsx
> +              ft
Шаблонизатор был бы кстати

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/FlightData/FlightData.tsx
> +              {airline.icao}
И тут

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/FlightInfo/FlightInfo.scss
> +    // width: 50%;
Уберём?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/FlightInfo/FlightInfo.tsx
> +  cityDestination: string
Запятых дефицит. Ну и интерфейс в отдельный файл бы

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/FlightInfo/FlightInfo.tsx
> +:JSX.Element => (
Пробел пропал

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/FlightInfo/FlightInfo.tsx
> +        )
Вот тут прям строка шаблонизатора во все лопатки просится

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/FlightProgress/FlightProgress.scss
> +      background: #f8C023;
К одному регистру давай приведёт буквы

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/FlightProgress/FlightProgress.tsx
> +import './FlightProgress.scss';
Мне очень нравится, когда импорты тоже упорядочены, например, сначала идут сторонние библиотеки, потом собственные компоненты, потом утилиты, а потом стили. Вкусовщина, поэтому не настаиваю

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/HeaderFlight/HeaderFlight.tsx
> +  closeHandler: () => void
зпт

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/RecentFlights/RecentFlights.scss
> +      fill: rgb(50, 125, 182);
Везде hex, а тут rgb. Может, унифицируем?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/RecentFlights/RecentFlights.tsx
> +          href={`https://www.flightradar24.com/data/aircraft/${registration.toLowerCase()}`}
А чего не через наш сервер?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/RecentFlights/RecentFlights.tsx
> +        </p> */}
Убираем?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/components/Flight/SVGComponents/Airborne.tsx
> +      style={{ fill: '#F8C024' }}
Давай к единому регистру приведём?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/utils/getFlightTime.tsx
> +export default getFlightTime;
Это же файл-утилита, а не компонент, зачем ему расширение .tsx?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/utils/getDistance.tsx
> +export default getDistance;
Это же файл-утилита, а не компонент, зачем ему расширение .tsx?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/utils/getDateHistory.tsx
> +export default getDateHistory;
Это же файл-утилита, а не компонент, зачем ему расширение .tsx?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/utils/addPlusMinusUTCTime.tsx
> +export default addPlusMinusUTCTime;
Это же файл-утилита, а не компонент, зачем ему расширение .tsx?

2021-01-31 17:22 UTC, lbratkovskaya commented on src/types/types.d.ts
> +};
Типы, которые используются в нескольких местах (типа "глобальные") можно сложить в index.d.ts. Тогда импортироваться они будут строкой: import ... from ./types (без указания конкретного файла)

2021-02-02 15:31 UTC, babkinevgeny requested changes

2021-02-02 15:31 UTC, babkinevgeny commented on src/components/Airport/ArrivalsAndDepartures/OneFlight/OneFlight.tsx
> +  let firstUrl: string;
может стоит разделить переменные и блок if пустыми строками?

2021-02-02 15:31 UTC, babkinevgeny commented on src/components/App/App.tsx
> +
точно нужна пустая строка?

2021-02-02 15:31 UTC, babkinevgeny commented on src/components/Flight/AircraftInfo/AircraftInfo.scss
> +  .row {
я сегодня магистр пустых строк) лучше отделять правила пустыми строками

2021-02-02 15:31 UTC, babkinevgeny commented on src/components/Flight/AircraftInfo/AircraftInfo.scss
> +    & img {
и тут

2021-02-02 15:31 UTC, babkinevgeny commented on src/components/Flight/AircraftInfo/AircraftInfo.tsx
> +  if (airline.iata && airline.icao) {
здесь тоже актуально

2021-02-02 15:44 UTC, Christina-Kashevar commented on src/components/App/App.tsx
> +
точно не нужна)

2021-02-02 15:45 UTC, lbratkovskaya requested changes

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Airport/Airport.scss
> +.opened {
Здесь селектор должен выглядеть:
```
&.opened
```
В противном случае scss парсер преобразует это в #airport .opened (.opened, вложенный в #airport)

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Airport/Airport.scss
> +.closed {
Аналогично здесь &.closed

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Airport/ScheduledFlights/ScheduledFlights.scss
> +    background-color: rgb(239, 239, 244);
Давай везде hex, ок?

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/Altitude/Altitude.tsx
> +    <div className="flight-altitude__icon"><AltitudeIcon /></div>
Не очень хорошо читается вложенность, когда элементы расположены в одну строку.
```
    <div className="flight-altitude__icon">
        <AltitudeIcon />
    </div>
```

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/FlightButton/FlightButton.scss
> +    fill: white;
Раз уж везде hex, то давай тут тоже hex

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/FlightButton/FlightButton.scss
> +      fill:#f8C023;
Пробел пропал

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/HeaderFlight/HeaderFlight.scss
> +    color: #f8C023;
Закралась заглавная С

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/HeaderFlight/HeaderFlight.scss
> +      fill: white;
hex

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/HeaderFlight/HeaderFlight.tsx
> +import './HeaderFlight.scss';
Давай стиль последним поставим? Везде так хорошо стоит последним, душа моя радуется)))

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/HeaderFlight/HeaderFlight.tsx
> +}:HeaderFlightPanelProps)
Пробел

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/HeaderFlight/HeaderFlight.tsx
> +:JSX.Element => (
И тут

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/RecentFlights/RecentFlights.scss
> +    background-color: #327DB6;
Буковки заглавные

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/RecentFlights/RecentFlights.scss
> +    border-bottom: solid 3px rgb(50, 125, 182);
Давай в hex?

2021-02-02 15:45 UTC, lbratkovskaya commented on src/components/Flight/Speed/Speed.scss
> +    background-color: rgb(239, 239, 244);
hex

2021-02-02 15:45 UTC, lbratkovskaya commented on src/utils/airportApiUtils.ts
> +// export const firstLogoUrl = (iata: string, icao: string): string => `/api/firstUrl?${iata}&${icao}`;
Уберём комментарий?

2021-02-02 15:50 UTC, Christina-Kashevar commented on src/components/Airport/Airport.scss
> +.opened {
я вынесла этот класс из скоупа airport, чтобы он был глобальным, т к он используется в нескольких местах

2021-02-02 15:50 UTC, Christina-Kashevar commented on src/components/Airport/Airport.scss
> +.closed {
тоже самое, есть в аэропортах и в рейсе)

2021-02-02 15:59 UTC, Christina-Kashevar commented on src/utils/airportApiUtils.ts
> +// export const firstLogoUrl = (iata: string, icao: string): string => `/api/firstUrl?${iata}&${icao}`;
конечно) упустила

2021-02-02 16:15 UTC, lbratkovskaya approved these changes

2021-02-02 18:01 UTC, lbratkovskaya approved these changes

2021-02-03 19:16 UTC, babkinevgeny approved these changes

2021-02-03 19:25 UTC, merged