Local storage
lbratkovskaya/flightradar-clone pull request #8
Opened 2021-02-01 10:32 UTC by lbratkovskaya

1. Save user map settings in local storage
2. Context menu finals: open airport panel's arrivals & departures on CM options click
3. Login form routing

2021-02-01 12:32 UTC, OlgaSenyushkina requested changes

2021-02-01 12:32 UTC, OlgaSenyushkina commented on src/components/Airport/index.tsx
> +            key={button.num}
button.num стоит обернуть в String(), так как key ожидает строку, а не число

2021-02-01 12:32 UTC, OlgaSenyushkina commented on src/components/App/App_arch.tsx
> +      console.log(res.data);
в идеале консоль логов в итоговой версии приложения не должно быть. 
Используем только при разработке фичи, но при её поставке лучше убирать)

2021-02-01 12:32 UTC, OlgaSenyushkina commented on src/components/App/App_arch.tsx
> +          onLoginRedirectHandler={() => {
эту функцию лучше вынести в метод и сюда передавать ссылку

2021-02-01 12:32 UTC, OlgaSenyushkina commented on src/components/App/index.tsx
> +      console.log(res.data);
здесь тоже не должно быть консоль лога

2021-02-01 12:32 UTC, OlgaSenyushkina commented on src/components/FlightsMap/MapStyleSelector/index.tsx
> +        key={key}
принято обычно сначала key указывать, а затем стили и остальные пропсы

2021-02-01 12:32 UTC, OlgaSenyushkina commented on src/components/FlightsMap/index.tsx
> +      || (prevUserData?.id !== userData?.id)) {
давай это условие в константу вынесем, чтобы было удобнее читать

2021-02-01 12:32 UTC, OlgaSenyushkina commented on src/types/index.d.ts
> +    {
Это можно разнести на несколько интерфейсов и их реиспользовать. Как-то так:

export interface LatLng {
  latitude: string,
  longitude: string
}
export interface ActionAirport {
    name: string,
    code: string,
    position: LatLng,
}
export interface favoriteItem: {
   addedToFavorites: Date,
   codeName: string,
    arrivalAirport: ActionAirport,
    departureAirport: ActionAirport,
}
export interface IUser {
  id: string,
  username: string,
  lastSessionEndedDate?: Date,
  favorites?: favoriteItem[],
}

2021-02-01 19:09 UTC, Christina-Kashevar approved these changes

2021-02-04 06:18 UTC, closed without merging

2021-02-04 06:18 UTC, lbratkovskaya commented
Merged within _all-in-one_ branch